### ISSUE TITLE
previous ship "re-placing" functionality broken

### ISSUE THREAD

**Issue by leian7** [OSU-CS361-W17/group20_project2#10]
Ships used to be able to be re-placed in new positions/orientations and represented as such to the user on the frontend; this was possible since the ``background-color`` of the user's board was first overwritten with blue before displaying the new game state with updated ship placements, which were represented with a yellow ``background-color``.

After merging in @kbajno 's attractive #7 , this functionality has been unwittingly deprecated since ``displayGameState`` is no longer able to overwrite a ``background-image`` with a mere ``background-color``!! The icons are transparent... now the user can theoretically fill up the board with 20 ``battleship``s' worth of ship icons even while the backend correctly reports the ``battleship``'s updated locations.

One way to fix this bug would be to replace the user board's blue ``background-color`` with a blue ``background-image`` that would essentially replace any old ship icons.

**Comment by aoleson** [comment]
Addressed by latest PR. Fixed :)
