### ISSUE TITLE
Handle errors and display error messages

### ISSUE THREAD

**Issue by aoleson** [OSU-CS361-W17/group20_project2#3]
- [x] Handle incorrect placement of ships: off the board + overlapping a preexisting ship
- [x] Implement an error message for each type of incorrect placement

**Comment by aoleson** [comment]
@leian7 You know how we were talking about firing at the same spot twice yesterday? I think the TAs put in some code that might help. Check BattleshipModel.java, line 119. Doesn't do anything but print it out, but it might be a place to start.

**Comment by leian7** [comment]
Resolved by #9
