### ISSUE TITLE
Implement clicking directly on enemy's board to fire

### ISSUE THREAD

**Issue by aoleson** [OSU-CS361-W17/group20_project2#4]
- [x] Handle click on enemy's grid at certain coordinates
- [x] Allow user to confirm whether to fire or scan at these coordinates
- [x] Implement view element for the above

**Comment by leian7** [comment]
@aoleson Do you anticipate doing something similar for scanning or should we ignore it this sprint in the interest of time?

**Comment by aoleson** [comment]
I'm actually integrating the scan feature as we speak :) Essentially, I have the user click a place on the board, then give them the option to either scan or fire at that place. It's going pretty well so far!

**Comment by leian7** [comment]
@aoleson Nice!!

**Comment by aoleson** [comment]
Finished in PR #6 . Done :)
